// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRDzLalDX5P-VrAkvuodZ8VIuhdQSuSI',
    appId: '1:128398320231:web:2a23564b8f297f88066ac2',
    messagingSenderId: '128398320231',
    projectId: 'hotelhubb-e1d01',
    authDomain: 'hotelhubb-e1d01.firebaseapp.com',
    storageBucket: 'hotelhubb-e1d01.appspot.com',
    measurementId: 'G-Z3CJGJWRGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJIxzB0yBhGK_EpCD7BSlRw8BrV7e_-pU',
    appId: '1:128398320231:android:8adefb649526205c066ac2',
    messagingSenderId: '128398320231',
    projectId: 'hotelhubb-e1d01',
    storageBucket: 'hotelhubb-e1d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbVW8Fg1RWVwEyLe_hMHJfDlp79rylqXQ',
    appId: '1:128398320231:ios:3a82eaf3a0b65e88066ac2',
    messagingSenderId: '128398320231',
    projectId: 'hotelhubb-e1d01',
    storageBucket: 'hotelhubb-e1d01.appspot.com',
    iosBundleId: 'com.example.hotelhubb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbVW8Fg1RWVwEyLe_hMHJfDlp79rylqXQ',
    appId: '1:128398320231:ios:5580b006e3dfd4a2066ac2',
    messagingSenderId: '128398320231',
    projectId: 'hotelhubb-e1d01',
    storageBucket: 'hotelhubb-e1d01.appspot.com',
    iosBundleId: 'com.example.hotelhubb.RunnerTests',
  );
}
